Update AutoSlugField's populate_from fields for new Django migrations
If you try to create an initial migration for Django's migration system
that was introduced in Django 1.7 you will get this error:

  ValueError: Cannot serialize function: lambda

... because the definitions of AutoSlugField use a lambda as the value
of populate_from. The easiest solution, as suggested here:

  https://docs.djangoproject.com/en/1.7/topics/migrations/#serializing-values

... is to make the value a module-level function instead of a lambda.